baseurl = "https://amy17519.me"
languageCode = "en-us"
title = "Amy Tzuyu Chen"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
enableEmoji = true
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 4
[[menu.main]]
    name = "Talks"
    url = "/talk/"
    weight = 5

[params]
    description = ""
    footer = "&copy; [Amy Tzuyu Chen](https://amy17519.me) 2018-2020 | [Github](https://github.com/amy17519) | [Twitter](https://twitter.com/amy17519) | [LinkedIn](https://www.linkedin.com/in/amy17519)"
